maintainer        "CrowdMob Inc."
maintainer_email  "developers@crowdmob.com"
license           "Apache 2.0"
description       "Install and deploy go web applications."
version           "0.0.1"
recipe            "goapp::configure"
recipe            "goapp::deploy"
recipe            "goapp::restart"
recipe            "goapp::rollback"
recipe            "goapp::stop"
recipe            "goapp::undeploy"
depends           "golang"
depends           "monit"
depends           "deploy"
