name              'goapp'
maintainer        "CrowdMob Inc."
maintainer_email  "developers@crowdmob.com"
license           "Apache 2.0"
description       "Install and deploy go web applications."
version           "0.0.1"
recipe            "goapp::configure", "This recipe configures goapp in OpsWorks stack"
recipe            "goapp::deploy", "This recipe deploys the goapp in OpsWorks stack"
recipe            "goapp::restart", "This recipe restarts the goapp in OpsWorks stack"
recipe            "goapp::rollback", "This recipe rolls back a deploy in OpsWorks stack"
recipe            "goapp::stop", "This recipe stops goapp in OpsWorks stack"
recipe            "goapp::undeploy", "This recipe undeploys app from OpsWorks stck"
depends           "golang"
depends           "monit"
depends           "deploy"
